schema: ./graphql.schema.json
documents: src/queries/**/*.{ts, tsx}
extensions:
  endpoints:
    default: http://157.230.108.68:3000/graphql
  graphql-codegen:
    generates:
      ./src/generated/types.ts:
        plugins:
          - typescript
          - typescript-resolvers
          - typescript-operations
          - typescript-react-apollo
        config:
          skipTypename: false
          withHooks: true
          withHOC: false
          withComponent: false

